#
# Build configuration for Circle CI
#


jobs:
  build:
     working_directory: ~/AndroidstudioProjects_new/ActivityLifeCycle
       steps:
        - run:
             name: "Test the commit for org or team processes"
                 command: |
                   echo "This is where we'd test this commit for things our project wants to enforce"
general:
    artifacts:
        - /home/ubuntu/ActivityLifeCycle/app/build/outputs/apk/

machine:
    environment:
        ANDROID_HOME: /usr/local/android-sdk-linux

dependencies:
    override:
        - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-19.1.0,android-19,extra-google-m2repository,extra-google-google_play_services,extra-android-support
        - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies

test:
    override:
        - (./gradlew assemble):
            timeout: 360